name       : yubikey-manager-qt
version    : 0.4.0
release    : 2
source     :
    - https://developers.yubico.com/yubikey-manager-qt/Releases/yubikey-manager-qt-0.4.0.tar.gz : 37c4e10e4cdaa65a49636e34f75191d02dc1be90cc7e9a035809d780dbf8de9a
license    : BSD-2-Clause
component  : security
summary    : Cross-platform application for configuring any YubiKey over all USB transports.
description: |
    Cross-platform application for configuring any YubiKey over all USB transports.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Qml)
rundeps    :
    - python-pyotherside
    - qt5-quickcontrols
    - yubikey-manager
setup      : |
    %qmake
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
    install -Dm644 $workdir/resources/ykman-gui.desktop $installdir/usr/share/applications/ykman-gui.desktop
    install -Dm644 $workdir/resources/icons/ykman.png $installdir/usr/share/pixmaps/ykman.png
