name       : yubikey-manager-qt
version    : 1.2.3
release    : 17
source     :
    - https://github.com/Yubico/yubikey-manager-qt/archive/refs/tags/yubikey-manager-qt-1.2.3.tar.gz : 995db5f072b353d6c6db492409f7b9ddfa8617bf5663695d83979bb443cc8520
license    : BSD-2-Clause
component  : security
summary    : Cross-platform application for configuring any YubiKey over all USB transports.
description: |
    Cross-platform application for configuring any YubiKey over all USB transports.
builddeps  :
    - pkgconfig(Qt5QuickControls2)
rundeps    :
    - python-pyotherside
    - qt5-quickcontrols
    - yubikey-manager
setup      : |
    %qmake
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
    install -Dm00644 $workdir/resources/ykman-gui.desktop $installdir/usr/share/applications/ykman-gui.desktop
    install -Dm00644 $workdir/resources/icons/ykman.png $installdir/usr/share/pixmaps/ykman.png
