name       : yubikey-manager-qt
version    : 1.2.5
release    : 19
source     :
    - https://github.com/Yubico/yubikey-manager-qt/archive/refs/tags/yubikey-manager-qt-1.2.5.tar.gz : 7f7106f0447713203cfa055eefbb82e0c4a3e5df3e451646da772ca24b174008
license    : BSD-2-Clause
component  : security
summary    : Cross-platform application for configuring any YubiKey over all USB transports.
description: |
    Cross-platform application for configuring any YubiKey over all USB transports.
builddeps  :
    - pkgconfig(Qt5QuickControls2)
rundeps    :
    - python-pyotherside
    - qt5-quickcontrols
    - yubikey-manager
setup      : |
    %qmake
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
    install -Dm00644 $workdir/resources/ykman-gui.desktop $installdir/usr/share/applications/ykman-gui.desktop
    install -Dm00644 $workdir/resources/icons/ykman.png $installdir/usr/share/pixmaps/ykman.png
