name       : yubikey-manager-qt
version    : 0.5.0
release    : 3
source     :
    - https://github.com/Yubico/yubikey-manager-qt/archive/yubikey-manager-qt-0.5.0.tar.gz : 0c68bfa0b97d3d39cdcbcb829e917f44581bc39602957cae9d0cbb77649b41ef
license    : BSD-2-Clause
component  : security
summary    : Cross-platform application for configuring any YubiKey over all USB transports.
description: |
    Cross-platform application for configuring any YubiKey over all USB transports.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Qml)
rundeps    :
    - python-pyotherside
    - qt5-quickcontrols
    - yubikey-manager
setup      : |
    %qmake
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
    install -Dm644 $workdir/resources/ykman-gui.desktop $installdir/usr/share/applications/ykman-gui.desktop
    install -Dm644 $workdir/resources/icons/ykman.png $installdir/usr/share/pixmaps/ykman.png
