name       : yubikey-manager-qt
version    : 1.0.1
release    : 8
source     :
    - https://github.com/Yubico/yubikey-manager-qt/archive/yubikey-manager-qt-1.0.1.tar.gz : 0845511bcec2b2cad7600a9ec576511f2b2be62541f17032a183b2fa5a20bdfd
license    : BSD-2-Clause
component  : security
summary    : Cross-platform application for configuring any YubiKey over all USB transports.
description: |
    Cross-platform application for configuring any YubiKey over all USB transports.
builddeps  :
    - pkgconfig(Qt5QuickControls2)
rundeps    :
    - python-pyotherside
    - qt5-quickcontrols
    - yubikey-manager
setup      : |
    %qmake
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
    install -Dm00644 $workdir/resources/ykman-gui.desktop $installdir/usr/share/applications/ykman-gui.desktop
    install -Dm00644 $workdir/resources/icons/ykman.png $installdir/usr/share/pixmaps/ykman.png
